// Warning: This file is auto-generated by ParseProtocol.exe, you should not change it!
// Time: 2017-03-05 14:31:14
using System;
using System.Text;

namespace NetIOLayer
{
    public class ServerMsgHandler
    {
        // Default handle of msg: GC_HeartBeat_Msg
        protected virtual bool OnGC_HeartBeat_Msg(GC_HeartBeat_Msg msg)
        {
            CSLogger.LogDebug("ServerMsgHandler: Recv msg: [" + msg.ToString() + "]");
            return false;
        }

        // Default handle of msg: GC_Echo_Response
        protected virtual bool OnGC_Echo_Response(GC_Echo_Response msg)
        {
            CSLogger.LogDebug("ServerMsgHandler: Recv msg: [" + msg.ToString() + "]");
            return false;
        }

        // Default handle of msg: GC_Chat_Msg
        protected virtual bool OnGC_Chat_Msg(GC_Chat_Msg msg)
        {
            CSLogger.LogDebug("ServerMsgHandler: Recv msg: [" + msg.ToString() + "]");
            return false;
        }

        // Msg dispatch function 
        protected bool DispatchMsg(Message msg)
        {
            if (null == msg)
            {
                return false;
            }
            if (msg.msg_id == GC_HeartBeat_Msg.MSG_ID) return OnGC_HeartBeat_Msg((GC_HeartBeat_Msg)msg);
            if (msg.msg_id == GC_Echo_Response.MSG_ID) return OnGC_Echo_Response((GC_Echo_Response)msg);
            if (msg.msg_id == GC_Chat_Msg.MSG_ID) return OnGC_Chat_Msg((GC_Chat_Msg)msg);
            CSLogger.LogError("Recv invalid msg id from GateServer: " + msg.msg_id);
            return false;
        }
    }
}
